name: mms
services:

  # Plex Media Server
  plex:
    image: lscr.io/linuxserver/plex
    container_name: ${CONTAINER_PREFIX}plex
    #Comment if you want to use `bridge` network_mode.
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=latest
      - PLEX_CLAIM=${PLEX_CLAIM}
    # Comment out if you are not using HW transcoding  
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${APPDATA_PATH}/plex:/config
      - ${DATA_PATH_ROOT}${DATA_PATH_MEDIA}:/media
      - /dev/shm/plex:/transcode
    ports:
      # Ports may cause a warning when used with `host` network mode, but would
      # allow switching without extra configuration.
      - 32400:32400
      - 1900:1900/udp
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    labels:
      - net.unraid.docker.icon=https://avatars.githubusercontent.com/u/324832?s=200&v=4
      - net.unraid.docker.webui=http://[IP]:[PORT:32400]/web
    restart: unless-stopped

  #Tautulli
  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: ${CONTAINER_PREFIX}tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/tautulli:/config
    ports:
      - 8181:8181
    networks:
      - default
      - internal
      - ${CF_NETWORK_INTERFACE}
    extra_hosts:
      - plex:host-gateway
    labels:
      - net.unraid.docker.icon=https://avatars.githubusercontent.com/u/34385001?s=200&v=4
      - net.unraid.docker.webui=http://[IP]:[PORT:8181]
    restart: unless-stopped

  #Plex Auto Languages
  plex-auto-languages:
    image: remirigal/plex-auto-languages
    container_name: ${CONTAINER_PREFIX}plex-auto-languages
    user: ${PUID}:${PGID}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - default
      - internal
    extra_hosts:
      - plex:host-gateway
    volumes:
      # make sure you have a file named 'config.yaml' in the 'config' dir
      - ${APPDATA_PATH}/plex-auto-languages:/config
    labels:
      - net.unraid.docker.icon=https://raw.githubusercontent.com/superboki/ressources/main/plex-auto-languages/plex_auto_languages.png
    restart: unless-stopped

  #Overseerr
  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: ${CONTAINER_PREFIX}overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/overseerr:/config
    ports:
      - 5055:5055
    networks:
      - default
      - internal
      - ${CF_NETWORK_INTERFACE}
    extra_hosts:
      - plex:host-gateway
    labels:
      - net.unraid.docker.icon=https://github.com/sct/overseerr/blob/develop/public/android-chrome-192x192.png?raw=true
      - net.unraid.docker.webui=http://[IP]:[PORT:5055]
    restart: unless-stopped

  #Radarr
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: ${CONTAINER_PREFIX}radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/radarr:/config
      - ${DATA_PATH_ROOT}:/data
    ports:
      - 7878:7878
    networks:
      - default
      - internal
    labels:
      - net.unraid.docker.icon=https://avatars.githubusercontent.com/u/25025331?s=200&v=4
      - net.unraid.docker.webui=http://[IP]:[PORT:7878]
    restart: unless-stopped

  radarr-4k:
    image: lscr.io/linuxserver/radarr
    container_name: ${CONTAINER_PREFIX}radarr-4k
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/radarr-4k:/config
      - ${DATA_PATH_ROOT}:/data
    ports:
      - 7879:7878
    networks:
      - default
      - internal
    labels:
      - net.unraid.docker.icon=https://avatars.githubusercontent.com/u/25025331?s=200&v=4
      - net.unraid.docker.webui=http://[IP]:[PORT:7879]
    restart: unless-stopped

  #Sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: ${CONTAINER_PREFIX}sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/sonarr:/config
      - ${DATA_PATH_ROOT}:/data
    ports:
      - 8989:8989
    networks:
      - default
      - internal
    labels:
      - net.unraid.docker.icon=https://avatars.githubusercontent.com/u/1082903?s=200&v=4
      - net.unraid.docker.webui=http://[IP]:[PORT:8989]
    restart: unless-stopped

  sonarr-4k:
    image: lscr.io/linuxserver/sonarr
    container_name: ${CONTAINER_PREFIX}sonarr-4k
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/sonarr-4k:/config
      - ${DATA_PATH_ROOT}:/data
    ports:
      - 8990:8989
    networks:
      - default
      - internal
    labels:
      - net.unraid.docker.icon=https://avatars.githubusercontent.com/u/1082903?s=200&v=4
      - net.unraid.docker.webui=http://[IP]:[PORT:8990]
    restart: unless-stopped

  #Bazarr
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: ${CONTAINER_PREFIX}bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/bazarr:/config
      - ${DATA_PATH_ROOT}${DATA_PATH_MEDIA}:/data/media
    ports:
      - 6767:6767
    networks:
      - default
      - internal
    labels:
      - net.unraid.docker.icon=https://avatars.githubusercontent.com/u/44780843?s=200&v=4
      - net.unraid.docker.webui=http://[IP]:[PORT:6767]
    restart: unless-stopped

  bazarr-4k:
    image: lscr.io/linuxserver/bazarr
    container_name: ${CONTAINER_PREFIX}bazarr-4k
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/bazarr-4k:/config
      - ${DATA_PATH_ROOT}${DATA_PATH_MEDIA}:/data/media
    ports:
      - 6768:6767
    networks:
      - default
      - internal
    labels:
      - net.unraid.docker.icon=https://avatars.githubusercontent.com/u/44780843?s=200&v=4
      - net.unraid.docker.webui=http://[IP]:[PORT:6768]
    restart: unless-stopped

  #Lidarr
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: ${CONTAINER_PREFIX}lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/lidarr:/config
      - ${DATA_PATH_ROOT}:/data
    ports:
      - 8686:8686
    networks:
      - default
      - internal
    extra_hosts:
      - plex:host-gateway
    labels:
      - net.unraid.docker.icon=https://lidarr.audio/img/logo.png
      - net.unraid.docker.webui=http://[IP]:[PORT:8686]
    restart: unless-stopped

  #Kometa
  kometa:
    image: kometateam/kometa
    container_name: ${CONTAINER_PREFIX}kometa
    user: ${PUID}:${PGID}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - KOMETA_CONFIG=/config/config.yml
      - KOMETA_TIMES=${KOMETA_TIMES}
      - KOMETA_RUN=${KOMETA_RUN}
      - KOMETA_TEST=${KOMETA_TEST}
    volumes:
      - ${APPDATA_PATH}/kometa:/config
    networks:
      - default
      - internal
    extra_hosts:
      - plex:host-gateway
    labels:
      - net.unraid.docker.icon=https://a.thumbs.redditmedia.com/jxT3aYQAjtC6QSKj7coUaL_xi3RPcg8Et5t-UbWNHf4.png
    restart: unless-stopped

  #Prowlarr
  prowlarr:
    image: linuxserver/prowlarr
    container_name: ${CONTAINER_PREFIX}prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 9696:9696
    networks:
      - internal
      - ${VPN_NETWORK_INTERFACE}
    labels:
      - net.unraid.docker.icon=https://avatars.githubusercontent.com/u/73049443?s=200&v=4
      - net.unraid.docker.webui=http://[IP]:[PORT:9696]
    volumes:
      - ${APPDATA_PATH}/prowlarr:/config
    restart: unless-stopped

  #Notifiarr
  notifiarr:
    image: golift/notifiarr
    container_name: ${CONTAINER_PREFIX}notifiarr
    user: ${PUID}:${PGID}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/notifiarr:/config
      - /var/run/utmp:/var/run/utmp

      - type: bind
        source: /etc/machine-id
        target: /etc/machine-id
        read_only: true
    ports:
      - 5454:5454
    networks:
      - default
      - internal
    extra_hosts:
      - plex:host-gateway
    labels:
      - net.unraid.docker.icon=https://avatars.githubusercontent.com/u/77931263?s=200&v=4
      - net.unraid.docker.webui=http://[IP]:[PORT:5454]
    restart: unless-stopped

  #FlareSolverr
  flaresolverr:
    #image: ghcr.io/flaresolverr/flaresolverr
    image: 21hsmw/flaresolverr:nodriver
    container_name: ${CONTAINER_PREFIX}flaresolverr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - LOG_LEVEL=info
      - LANG=en_US
    ports:
      - 8191:8191
    networks:
      - internal
      - ${VPN_NETWORK_INTERFACE}
    labels:
      - net.unraid.docker.icon=https://avatars.githubusercontent.com/u/75936191?s=200&v=4
      - net.unraid.docker.webui=http://[IP]:[PORT:8191]
    restart: unless-stopped

  #Sabnzbd
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    container_name: ${CONTAINER_PREFIX}sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/sabnzbd:/config
      - ${DATA_PATH_ROOT}${DATA_PATH_DOWNLOAD}:/data/download
    ports:
      - 7226:8080
    networks:
      - default
      - internal
    extra_hosts:
      - plex:host-gateway
    labels:
      - net.unraid.docker.icon=https://avatars.githubusercontent.com/u/960698?s=200&v=4
      - net.unraid.docker.webui=http://[IP]:[PORT:7226]
    restart: unless-stopped

  #Syncthing
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: ${CONTAINER_PREFIX}syncthing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/syncthing:/config
      - ${DATA_PATH_ROOT}${DATA_PATH_DOWNLOAD}/qbittorrent:/data/download/qbittorrent
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    networks:
      - default
    labels:
      - net.unraid.docker.icon=https://avatars.githubusercontent.com/u/7628018?s=200&v=4
      - net.unraid.docker.webui=http://[IP]:[PORT:8384]
    restart: unless-stopped

  #Unpackerr
  unpackerr:
    image: golift/unpackerr
    container_name: ${CONTAINER_PREFIX}unpackerr
    user: ${PUID}:${PGID}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/unpackerr:/config
      - ${DATA_PATH_ROOT}${DATA_PATH_DOWNLOAD}:/data/download
    networks:
      - default
      - internal
    labels:
      - net.unraid.docker.icon=https://avatars.githubusercontent.com/u/104323643?s=200&v=4
    restart: unless-stopped

  #Posterr
  posterr:
    image: petersem/posterr
    container_name: ${CONTAINER_PREFIX}posterr
    environment:
      TZ: ${TZ}
    volumes:
      - ${APPDATA_PATH}/posterr:/usr/src/app/config
      - ${APPDATA_PATH}/posterr/custom:/usr/src/app/public/custom
    ports:
      - 3000:3000
    networks:
      - default
      - internal
    extra_hosts:
      - plex:host-gateway
    labels:
      - net.unraid.docker.icon=https://avatars.githubusercontent.com/u/1418289?s=48&v=4
      - net.unraid.docker.webui=http://[IP]:[PORT:3000]
    restart: unless-stopped

  #Calibre Web
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: ${CONTAINER_PREFIX}calibre-web
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ${APPDATA_PATH}/calibre-web:/config
      - ${DATA_PATH_ROOT}${DATA_PATH_MEDIA}/books:/books
    ports:
      - 8083:8083
    networks:
      - default
      - internal
      - ${CF_NETWORK_INTERFACE}
    labels:
      - net.unraid.docker.icon=https://static-00.iconduck.com/assets.00/calibreweb-icon-512x512-snhnkujz.png
      - net.unraid.docker.webui=http://[IP]:[PORT:8083]
    restart: unless-stopped
    
#Networking
networks:
  internal:
    internal: true
    name: mms_internal
  #Remove or replace depending on your VPN external network
  wg0:
    external: true
  #Remove or replace depending on your cloudflared external network
  cloudflared:
    external: true
